# Project Managment {#managment}

### *Introduction*

While not directly related to data management, bad project management will cripple your ability to keep track of data, produce new data, and complete your interdisciplinary project in a timely manner.  More than many other projects, good communication & project planning from the very beginning is critical for an interdisciplinary & highly collaborative project - as several teams will be bringing their own workflows & communication channels to the table.  

### *Questions to Consider*

-   What are the specific goals and outputs for the project?  For your team?  Do different teams have different goals in mind for this project?
-   What communication channels will be used?  Will data be shared through these channels?  How will the team update each other on data changes?  
-   Who is responsible for the data?  Will different teams be in charge of different data sets?  Who is ultimately responsible for quality control of which outputs?  


### *Pitfalls*

There are several potential pitfalls to poor project management.  From a data prospective - poor project management can quickly lead to disorganized file storage, miss communication on project goals, scope creep, and unclear roles on who is responsible for the data.   

### *Additional Resources*

While project management is important, it is not the focus of this tutorial - for more information on planning your IHCR project, please refer to this project charter. [LINK](https://docs.google.com/document/d/1BglLx4rkEUubUDj_EweI2wVELu_u7OdF/edit)
